test: &default

  # Credentials for REST APIs
  client_id: AfHXSJIph-k7cZLG48RUx-kaou1X9NY1cms1qUYD29laY8HpHt4G-yN0u0rhy14cEe5iI-_jD-pZsmn6
  client_secret: EJDX84UwZ6uk1ZjMVsmL4dCOW9n55WMXhOi8bk4SgnBKdaK1ilYc-wH7M0P-WECsipn_VccGbM5iVC66

  ssl_options: { ca_file: nil }
  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: jb-us-seller_api1.paypal.com
  password: WX4WTU3S8MY44S7F
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: Platform.sdk.seller@gmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live

ssl_options:
  ca_file: null
